### ISSUE TITLE
".mat" files from the MAFA dataset

### ISSUE THREAD

**Issue by parasmehan123** [DhyeyLalseta/MAFAExtractor#1]
Hi, 
Can anyone tell me where I can get ".mat" files for the MAFA dataset?

**Comment by dhyxy** [comment]
> Hi, 
> 
> Can anyone tell me where I can get ".mat" files for the MAFA dataset?

I think because of the traffic for the dataset the official website's down. But this is the google drive link for the dataset, let me know if it works and feel free to star the repo if the tool proves to be useful🌟


https://drive.google.com/drive/folders/1nbtM1n0--iZ3VVbNGhocxbnBGhMau_OG

**Comment by parasmehan123** [comment]
Thanks!
